name: biblebaptist
favicon: null
layout_spectrum: 0.9269541797693819
typography_spectrum: 0.9927233713679016
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.024701632792130113
  lightness: 0.4107586860191077
  saturation: 0.8535109828226268
  rhythmicContrast: 0.724597203778103
purpose: []
